Corrected 0x0C-web_server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,26 @@
-#!/bin/bash
-
-# Check if the number of parameters is less than 4
-if [ "$#" -lt 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+#!/usr/bin/env bash
+# Checks 4 command-line args
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# Assign parameters to variables
-file_path=$1
-server_ip=$2
+# Assigning Arguments to variables
+
+path_to_file=$1
+ip=$2
 username=$3
-ssh_key_path=$4
+path_to_ssh_key=$4
 
-# Use scp to transfer the file to the user's home directory (~)
-scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/
 
-# Check if scp command was successful
-if [ $? -eq 0 ]; then
-    echo "File transfer successful"
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-    echo "File transfer failed"
+  echo "FILE TRANSFER FAILED"
 fi
